first try
maximboltinov/java-filmorate pull request #4
Opened 2023-11-06 23:03 UTC by maximboltinov

2023-11-10 15:22 UTC, YazykovMikhail commented
Все замечание приминятся сразу и к фильмам и к пользователям

2023-11-10 15:22 UTC, YazykovMikhail requested changes

2023-11-10 15:22 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private static final Gson gson = new GsonBuilder()
статические переменные обьявялются первыми по кодстайлу

2023-11-10 15:22 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private static int idCounter = 1;
не надо static, статик значит поле принадлежит классу, но это поле принадлежит обьекту, у каждого сервиса с фильмами будут свои  идентификаторы, а не одни для ввсех

поправь и для User

2023-11-10 15:22 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        System.out.println("film = " + film);
через log.info
 System.out.println("film = " + film); уже не используем)

2023-11-10 15:22 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private String filmValidation(Film film) {
воозвращат ьстроку это не очень, выбрасывай исключение, например вот так:
void validate(Film data) {
		if (data.getName() == null || data.getName().isEmpty()) {
			throw new ValidationException("Film name invalid");
		}
		if (data.getDescription() != null && data.getDescription().length() > MAX_NAME_SIZE) {
			throw new ValidationException("Film description invalid");
		}
		if (data.getReleaseDate() == null || data.getReleaseDate().isBefore(FILM_BIRTHDAY)) {
			throw new ValidationException("Film release date invalid");
		}
		if (data.getDuration() <= 0) {
			throw new ValidationException("Film duration invalid");
		}
	}

2023-11-10 23:38 UTC, maximboltinov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private static final Gson gson = new GsonBuilder()
idCounter убрал static
Убрал gson

2023-11-10 23:39 UTC, maximboltinov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private static int idCounter = 1;
Убрал static

2023-11-11 22:07 UTC, maximboltinov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            user.setName(user.getLogin());
POST и PUT сделал log.info

2023-11-11 22:14 UTC, maximboltinov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        String message = filmValidation(film);
+ оба Controller

2023-11-11 23:37 UTC, maximboltinov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public String findAll() {
реализовал для обеих Controller

2023-11-12 13:19 UTC, maximboltinov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private String filmValidation(Film film) {
Реализовал исключения  в методе валидации для обеих Controller.

2023-11-12 13:19 UTC, maximboltinov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (!message.isEmpty()) {
Реализовал исключения  в методе валидации для обеих Controller

2023-11-13 01:38 UTC, maximboltinov commented
Поиграл с наследованием. Так можно?
Устранил остальные замечания.

2023-11-13 09:48 UTC, YazykovMikhail approved these changes

2023-11-13 09:48 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw e;
вот так будет красивее
            log.error("Запрос завершен ошибкой: " + e.getMessage());
            throw new ValidationException("Такой фильм уже существует");

2023-11-13 09:48 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        try {
не надо тут обрабатывать, ты получается просто обрабатываешь и выкидываешь одно и тоже исключение, этого не нужно, просто вызывай метод валидации и все

2023-11-13 09:48 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        try {
не надо тут обрабатывать, ты получается просто обрабатываешь и выкидываешь одно и тоже исключение, этого не нужно, просто вызывай метод валидации и все

2023-12-01 13:36 UTC, merged